name: ${project.name}
version: ${project.version}
author: Garris0n
main: com.garris0n.EntityGUI.Main
commands:
  entityGUI:
    aliases: egui
    permission: EntityGUI.use
    usage: /entitygui
    permission-message: ยง4You do not have permission to use this command.